# -*- coding: utf-8 -*-
import keyring
enedis_pass1 = keyring.get_password("enedis","pass1")
enedis_key1 = keyring.get_password("enedis","key1")
polen_mail_user_production = keyring.get_password("polen","mail_user_production")
polen_mail_user_production = keyring.get_password("polen","mail_user_production")
polen_mail_pass_production = keyring.get_password("polen","mail_pass_production")
polen_mail_pass_production = keyring.get_password("polen","mail_pass_production")
polen_db_user_polen = keyring.get_password("configuration","db_user_polen")
polen_db_pass_polen = keyring.get_password("configuration","db_pass_polen")
configuration_db_user_localhost = keyring.get_password("configuration","db_user_localhost")
configuration_db_pass_localhost = keyring.get_password("configuration","db_pass_localhost")
polen_ftp_user_hydronext = keyring.get_password("polen","ftp_user_hydronext")
polen_ftp_pass_hydronext = keyring.get_password("polen","ftp_pass_hydronext")
polen_ftp_user_eex = keyring.get_password("polen","ftp_user_eex")
polen_ftp_pass_eex = keyring.get_password("polen","ftp_pass_eex")
polen_ftp_user_cnr = keyring.get_password("polen","ftp_user_cnr")
polen_ftp_pass_cnr = keyring.get_password("polen","ftp_pass_cnr")
polen_ftp_user_enercoop = keyring.get_password("polen","ftp_user_enercoop")
polen_ftp_pass_enercoop = keyring.get_password("polen","ftp_pass_enercoop")
